2019-10-31 10:33:57 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "DATABASECHANGELOGLOCK" not found; SQL statement:
SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK [42102-197]
2019-11-29 00:08:53 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-11-29 00:10:14 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-11-29 00:40:49 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-11-29 00:52:28 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-11-29 01:15:29 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-11-29 01:35:47 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-12-05 09:00:03 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
2019-12-06 09:00:02 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:387)
	at clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:672)
	at clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:619)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1094)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at toucan.db$query.invokeStatic(db.clj:285)
	at toucan.db$query.doInvoke(db.clj:281)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:391)
	at toucan.db$simple_select.invoke(db.clj:380)
	at toucan.db$select.invokeStatic(db.clj:659)
	at toucan.db$select.doInvoke(db.clj:653)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49808$table__GT_fields__49813$fn__49814.invoke(fetch_metadata.clj:63)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49808$table__GT_fields__49813.invoke(fetch_metadata.clj:60)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49831$our_metadata__49836$fn__49837.invoke(fetch_metadata.clj:71)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49831$our_metadata__49836.invoke(fetch_metadata.clj:67)
	at metabase.sync.sync_metadata.fields$fn__50331$sync_and_update_BANG___50336$fn__50337.invoke(fields.clj:76)
	at metabase.sync.sync_metadata.fields$fn__50331$sync_and_update_BANG___50336.invoke(fields.clj:72)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368$fn__50374$fn__50376.invoke(fields.clj:102)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368$fn__50374.invoke(fields.clj:90)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368.invoke(fields.clj:83)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410$iter__50411__50415$fn__50416$fn__50417.invoke(fields.clj:117)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410$iter__50411__50415$fn__50416.invoke(fields.clj:116)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410.invoke(fields.clj:116)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409.invoke(fields.clj:111)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415$fn__41419$fn__41421.invoke(util.clj:356)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415$fn__41419.invoke(util.clj:353)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415.invoke(util.clj:348)
	at metabase.sync.util$fn__41602$run_sync_operation__41607$fn__41608$fn__41609.invoke(util.clj:441)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__41602$run_sync_operation__41607$fn__41608.invoke(util.clj:441)
	at metabase.sync.util$fn__41602$run_sync_operation__41607.invoke(util.clj:435)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096$fn__51097$fn__51098.invoke(sync_metadata.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver.mongo$eval2154$fn__2155$f__857__auto____2156.invoke(mongo.clj:73)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2154$fn__2155.invoke(mongo.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41316.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__41313.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__41302.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__41297.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41288.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:168)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:165)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096$fn__51097.invoke(sync_metadata.clj:50)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096.invoke(sync_metadata.clj:47)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:02 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:476)
	at com.mchange.v2.c3p0.impl.C3P0ImplUtils.resetTxnState(C3P0ImplUtils.java:245)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.reset(NewPooledConnection.java:461)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.markClosedProxyConnection(NewPooledConnection.java:417)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.close(NewProxyConnection.java:87)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at toucan.db$query.invokeStatic(db.clj:285)
	at toucan.db$query.doInvoke(db.clj:281)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:391)
	at toucan.db$simple_select.invoke(db.clj:380)
	at toucan.db$select.invokeStatic(db.clj:659)
	at toucan.db$select.doInvoke(db.clj:653)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49808$table__GT_fields__49813$fn__49814.invoke(fetch_metadata.clj:63)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49808$table__GT_fields__49813.invoke(fetch_metadata.clj:60)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49831$our_metadata__49836$fn__49837.invoke(fetch_metadata.clj:71)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__49831$our_metadata__49836.invoke(fetch_metadata.clj:67)
	at metabase.sync.sync_metadata.fields$fn__50331$sync_and_update_BANG___50336$fn__50337.invoke(fields.clj:76)
	at metabase.sync.sync_metadata.fields$fn__50331$sync_and_update_BANG___50336.invoke(fields.clj:72)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368$fn__50374$fn__50376.invoke(fields.clj:102)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368$fn__50374.invoke(fields.clj:90)
	at metabase.sync.sync_metadata.fields$fn__50359$sync_fields_for_table_BANG___50368.invoke(fields.clj:83)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410$iter__50411__50415$fn__50416$fn__50417.invoke(fields.clj:117)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410$iter__50411__50415$fn__50416.invoke(fields.clj:116)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409$fn__50410.invoke(fields.clj:116)
	at metabase.sync.sync_metadata.fields$fn__50404$sync_fields_BANG___50409.invoke(fields.clj:111)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415$fn__41419$fn__41421.invoke(util.clj:356)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415$fn__41419.invoke(util.clj:353)
	at metabase.sync.util$fn__41410$run_step_with_metadata__41415.invoke(util.clj:348)
	at metabase.sync.util$fn__41602$run_sync_operation__41607$fn__41608$fn__41609.invoke(util.clj:441)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__41602$run_sync_operation__41607$fn__41608.invoke(util.clj:441)
	at metabase.sync.util$fn__41602$run_sync_operation__41607.invoke(util.clj:435)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096$fn__51097$fn__51098.invoke(sync_metadata.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver.mongo$eval2154$fn__2155$f__857__auto____2156.invoke(mongo.clj:73)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2154$fn__2155.invoke(mongo.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41316.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__41313.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__41302.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__41297.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41288.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:168)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:165)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096$fn__51097.invoke(sync_metadata.clj:50)
	at metabase.sync.sync_metadata$fn__51091$sync_db_metadata_BANG___51096.invoke(sync_metadata.clj:47)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:03 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:387)
	at clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:672)
	at clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:619)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1094)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at toucan.db$query.invokeStatic(db.clj:285)
	at toucan.db$query.doInvoke(db.clj:281)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:391)
	at toucan.db$simple_select.invoke(db.clj:380)
	at toucan.db$select.invokeStatic(db.clj:659)
	at toucan.db$select.doInvoke(db.clj:653)
	at clojure.lang.RestFn.invoke(RestFn.java:559)
	at metabase.sync.util$db__GT_sync_tables.invokeStatic(util.clj:252)
	at metabase.sync.util$db__GT_sync_tables.invoke(util.clj:249)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341$fn__49342$fn__49343.invoke(analyze.clj:125)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver.mongo$eval2154$fn__2155$f__857__auto____2156.invoke(mongo.clj:73)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2154$fn__2155.invoke(mongo.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41316.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__41313.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__41302.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__41297.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41288.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:168)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:165)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341$fn__49342.invoke(analyze.clj:124)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341.invoke(analyze.clj:119)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:03 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:476)
	at com.mchange.v2.c3p0.impl.C3P0ImplUtils.resetTxnState(C3P0ImplUtils.java:245)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.reset(NewPooledConnection.java:461)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.markClosedProxyConnection(NewPooledConnection.java:417)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.close(NewProxyConnection.java:87)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at toucan.db$query.invokeStatic(db.clj:285)
	at toucan.db$query.doInvoke(db.clj:281)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:391)
	at toucan.db$simple_select.invoke(db.clj:380)
	at toucan.db$select.invokeStatic(db.clj:659)
	at toucan.db$select.doInvoke(db.clj:653)
	at clojure.lang.RestFn.invoke(RestFn.java:559)
	at metabase.sync.util$db__GT_sync_tables.invokeStatic(util.clj:252)
	at metabase.sync.util$db__GT_sync_tables.invoke(util.clj:249)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341$fn__49342$fn__49343.invoke(analyze.clj:125)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver.mongo$eval2154$fn__2155$f__857__auto____2156.invoke(mongo.clj:73)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2154$fn__2155.invoke(mongo.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41316.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__41313.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__41302.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__41297.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41288.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:168)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:165)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341$fn__49342.invoke(analyze.clj:124)
	at metabase.sync.analyze$fn__49336$analyze_db_BANG___49341.invoke(analyze.clj:119)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:03 jdbc[19]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:476)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.getAutoCommit(NewProxyConnection.java:1226)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:90)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:66)
	at com.sun.proxy.$Proxy11.setAutoCommit(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:788)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3788)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3760)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggeredJobComplete(JobStoreSupport.java:3000)
	at org.quartz.core.QuartzScheduler.notifyJobStoreJobComplete(QuartzScheduler.java:1753)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:281)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:03 jdbc[19]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:387)
	at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy11.prepareStatement(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:88)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3791)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3760)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggeredJobComplete(JobStoreSupport.java:3000)
	at org.quartz.core.QuartzScheduler.notifyJobStoreJobComplete(QuartzScheduler.java:1753)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:281)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2019-12-06 09:00:03 database: close
org.h2.message.DbException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.delete(FilePathDisk.java:160)
	at org.h2.store.fs.FilePathWrapper.delete(FilePathWrapper.java:88)
	at org.h2.store.fs.FileUtils.delete(FileUtils.java:66)
	at org.h2.mvstore.MVStoreTool.compact(MVStoreTool.java:449)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:386)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1439)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: org.h2.jdbc.JdbcSQLException: Cannot delete file "/metabase.db/metabase.db.mv.db" [90025-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 10 more
